backend/core/settings.py

fix: allow localhost in backend settings

---

.circleci/config.yml

fix: update circleci v1

---

.circleci/config.yml

ci: update ci v2

---

frontend/src/App.js
frontend/src/containers/Header.js
frontend/src/containers/NewsComponent.js
frontend/src/containers/NewsDetail.js
frontend/src/containers/NewsListing.js
frontend/src/redux/actions/newsActions.js
frontend/src/redux/contants/news-action-types.js
frontend/src/redux/reducers/index.js
frontend/src/redux/reducers/newReducer.js

Finished News Components with Redux. Using Axios.

feat: News Components

---

frontend/src/App.js
frontend/src/containers/UserFeedBack.js

feat: add rating page

---

frontend/src/components/Market/MarketComponent.js
frontend/src/components/Market/marketForm.js
frontend/src/containers/market/Market.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/marketFilterLocation.js
frontend/src/containers/market/marketImgTopFilter.js
frontend/src/containers/market/marketItemCss.js
frontend/src/containers/market/marketItemFilter.js
frontend/src/containers/market/marketItemFilterInfo.js
frontend/src/containers/market/marketItemSearch.js
frontend/src/containers/market/marketList.js
frontend/src/containers/market/marketSideBar.js
frontend/src/containers/market/marketVehicle.js

give me a large smiling face!😆😆😆

feat: new market vehicle list

---

frontend/src/containers/market/Market.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/PostMarketRental.js
frontend/src/containers/market/PostMarketVehicle.js
frontend/src/containers/market/marketImgTopFilter.js
frontend/src/containers/market/marketItemFilter.js
frontend/src/containers/market/marketItemFilterInfo.js
frontend/src/containers/market/marketRental.js

Give a huuuugggggge smiling face!🥸🥸🥸

feat: new market rental list

---

frontend/src/components/Market/MarketComponent.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/containers/market/marketFilterLocation.js
frontend/src/containers/market/marketImgTopFilter.js
frontend/src/containers/market/marketItem.js
frontend/src/containers/market/marketItemCss.js
frontend/src/containers/market/marketItemFilter.js
frontend/src/containers/market/marketItemFilterInfo.js
frontend/src/containers/market/marketItemSearch.js
frontend/src/containers/market/marketList.js
frontend/src/containers/market/marketRental.js
frontend/src/containers/market/marketSideBar.js
frontend/src/containers/market/marketTopBar.js
frontend/src/containers/market/marketVehicle.js

Me wanna biggggggg smiling face! 😈 😈 😈

fix: fixed some market bugs

---

frontend/src/components/Market/MarketComponent.js
frontend/src/components/Market/marketFilterLocation.js
frontend/src/components/Market/marketImgTopFilter.js
frontend/src/components/Market/marketItemCss.js
frontend/src/components/Market/marketItemFilter.js
frontend/src/components/Market/marketItemFilterInfo.js
frontend/src/components/Market/marketItemOptions.js
frontend/src/components/Market/marketItemSearch.js
frontend/src/components/Market/marketQueries.js
frontend/src/components/Market/marketRentalOptions.js
frontend/src/components/Market/marketSideBar.js
frontend/src/components/Market/marketTopBar.js
frontend/src/components/Market/marketVehicleOptions.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/PostMarketRental.js
frontend/src/containers/market/PostMarketVehicle.js
frontend/src/containers/market/marketItem.js
frontend/src/containers/market/marketList.js
frontend/src/containers/market/marketRental.js
frontend/src/containers/market/marketVehicle.js
frontend/src/redux/reducers/index.js
frontend/src/redux/reducers/marketSlice.js
frontend/src/redux/store.js

Give me a hugggggggeeeeeee smiling face!!!!🤐🤐🤐🤐

fix: fix market bugs

---

frontend/src/components/CustomMUI/CustomTags.js
frontend/src/components/Market/SwipeViews.js
frontend/src/components/Market/marketForm.js
frontend/src/components/Market/marketItemCss.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/PostMarketRental.js
frontend/src/containers/market/marketItem.js
frontend/src/containers/market/marketRental.js
frontend/src/containers/market/marketVehicle.js
frontend/src/redux/reducers/marketSlice.js

feat: new market post interface

---

frontend/src/containers/UserFeedBack.js

feat: adjust UI, add API call

---

frontend/src/components/CustomMUI/CustomAlert.js
frontend/src/components/CustomMUI/CustomTags.js
frontend/src/components/Market/marketForm.js
frontend/src/components/Market/marketItemFilterInfo.js
frontend/src/containers/market/MarketCreate.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/PostMarketRental.js
frontend/src/containers/market/PostMarketVehicle.js
frontend/src/redux/reducers/marketSlice.js

you know... HUGGGGGGEEEEEEE SMILING FACE!!!!!!!!!!😸😸😸😸😸😸😸😸😸😸😸

feat: new new market post interface

---

frontend/src/Hooks/useHover.js
frontend/src/components/Market/MarketComponent.js
frontend/src/containers/market/MarketCarpoolDetail.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketPetDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/containers/market/PostMarketCarpool.js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/PostMarketPet.js
frontend/src/containers/market/PostMarketRental.js
frontend/src/containers/market/PostMarketVehicle.js

fix: fix market post bugs

---

frontend/src/containers/market/EditMarketItemDetail.js
frontend/src/containers/market/Market.js
frontend/src/containers/market/MarketCarpoolDetail.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketPetDetail.js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/PostMarketPet.js
frontend/src/containers/market/PostMarketRental.js
frontend/src/containers/market/PostMarketVehicle.js
frontend/src/redux/reducers/marketSlice.js

🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮

fix:fix some market bugs

---

frontend/src/components/Event/EventMain.js
frontend/src/components/Event/PastEvents.js
frontend/src/components/Event/tag.js
frontend/src/containers/Event/Event.js

1. update event UI (edit EventMain.js)
2. use filter to divide events into recent and past events by current date (edit Event.js)
3. add a section for past events (add PastEvents.js and tag.js)

feat: divide events into recent and past events by current date

---

frontend/src/components/Event/PastEvents.js
frontend/src/components/Event/tag.js

change "close" tag to "past event" tag and update UI

refactor: change close tag

---

frontend/src/components/Event/EventBody.js
frontend/src/components/Event/EventMain.js
frontend/src/components/Event/PastEvents.js
frontend/src/components/Event/tag.js

1. closed events can be accessed but visitors cannot register
2. add tags to all cards

refactor: closed events can be accessed and add tags to all cards

---

frontend/src/components/Market/loading.js
frontend/src/components/Market/marketImgTopFilter.js
frontend/src/components/Market/marketTopBar.js
frontend/src/containers/market/EditMarketItemDetail.js
frontend/src/containers/market/EditMarketRentalDetail.js
frontend/src/containers/market/EditMarketVehicleDetail.js
frontend/src/containers/market/Market.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/containers/market/PostMarketCarpool.js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/PostMarketRental.js
frontend/src/containers/market/PostMarketVehicle.js
frontend/src/redux/reducers/marketSlice.js

🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐🧐

feat: new market edit interface

---

frontend/src/components/Event/EventBody.js

1. feat: add testing to see if someone has already registered for the event
2. fix: fix count of people going problem

fix: fix count of people going problem; feat: add testing to see if someone has already registered for the event

---

frontend/src/containers/market/EditMarketItemDetail.js
frontend/src/containers/market/EditMarketRentalDetail.js
frontend/src/containers/market/EditMarketVehicleDetail.js
frontend/src/containers/market/MarketCarpoolDetail.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketPetDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/containers/market/PostMarketCarpool.js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/PostMarketPet.js
frontend/src/containers/market/PostMarketRental.js
frontend/src/containers/market/PostMarketVehicle.js

🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯

feat: new detail contact

---

frontend/src/components/Market/marketQueries.js
frontend/src/containers/market/EditMarketItemDetail.js
frontend/src/containers/market/EditMarketRentalDetail.js
frontend/src/containers/market/EditMarketVehicleDetail.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/PostMarketItem.js
frontend/src/redux/reducers/marketUserSlice.js
frontend/src/redux/store.js

👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍ …

feat: new marketUserInfo

---

frontend/src/App.js
frontend/src/containers/market/MarketItemDetail.js
frontend/src/containers/market/MarketRentalDetail.js
frontend/src/containers/market/MarketVehicleDetail .js
frontend/src/redux/reducers/marketSlice.js

🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

fix: fix bugs dealing with bad uuids

---

frontend/src/components/Event/ArrowBack.js
frontend/src/components/Event/EventDetail.js
frontend/src/components/Event/EventMain.js
frontend/src/components/Event/PostEvent.js
frontend/src/containers/Event/Event.js

1. fix bugs
2. add useForm to post event

fix: fix event

---

frontend/src/components/Market/postCss.js
frontend/src/components/Market/swipeableDrawer.js
frontend/src/containers/market/PostMarketCarpool.js
frontend/src/containers/market/PostMarketItem.js
frontend/src/containers/market/previewInfo.js

probly gonna use "useForm" later on

factor: refactoring some market posts

---

frontend/src/components/Auth/SignUpRequireDialog.js
frontend/src/components/Event/EventBody.js
frontend/src/components/Event/EventDetail/Share.js
frontend/src/components/Event/EventMain.js
frontend/src/components/Event/PastEvents.js
frontend/src/components/Event/individual.js

1. edit UI
2. add share button

Fix event 

---

frontend/src/components/Account/Profile/Info/Edit.js
frontend/src/components/Account/Profile/Info/canvasUtils.js
frontend/src/components/Account/Profile/Info/dataURLtoFile.js

feat: add image cropper to personal homepage

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Event/EventBody.js
frontend/src/components/Event/EventDetail.js
frontend/src/components/Event/EventMain.js
frontend/src/components/Home/UwcssaIntro.js
frontend/src/containers/event/Event.js

add moment-timezone  to package.json

fix: apply moment-timezone
